server:
  port: 8780

eureka:
  instance:
    hostname: localhost
    #表示client间隔多久去拉去服务注册信息，default:30s,如果想快速拉取，可以缩小该值
    lease-renewal-interval-in-seconds: 5
    #表示client超出多长时间没有发送心跳就会被eureka server判定为死亡，default:90s
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product